site_name: Learn Security
theme:
  name: material
  language: zh
  palette:
    primary: light-blue
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
 